name: ecomm
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  cloud_firestore: ^3.1.7
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.1.1
  flutter_staggered_grid_view: ^0.6.1
  google_sign_in: ^5.2.3
  http: ^0.13.4
  intl: ^0.17.0
  paytm_allinonesdk: ^1.1.4
  shared_preferences: ^2.0.12

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  assets:
  - assets/images/
  - assets/fonts/
  - .env

  fonts:
    - family: ZillaSlab
      fonts:
        - asset: assets/fonts/ZillaSlab-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
  uses-material-design: true
  generate: true
